# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:
#  db:
 #   container_name: nimbler_db
  #  environment:
   #   - POSTGRES_PASSWORD=postgres
    #networks:
     # - shared-network
    #image: postgres:11.1-alpine
    #ports:
     # - 5433:5432
    # This is the core CRUD based service.
  key-generator-api:
    container_name: key-generator
    networks:
      - shared-network
    image: igorgomonov/key-generator-amd64:1.0
    ports:
      - 7000:7000 # CRUD API
      - 8000:8000 # DEBUG API
